<h1>Nuevo usuario</h1>

<form method="post" action="">

    <input type="hidden" name="action" value="save">

    <label for="input-name">Nombre</label>
    <input type="text" name="name" id="input-name" placeholder="Nombre" required>


    <label for="input-lastname">Apellidos</label>
    <input type="text" name="lastname" id="input-lastname" placeholder="Apellidos" required>

    <button type="submit">GUARDAR</button>

    <a href="/user/list">VER GUARDADOS</a>
</form>